# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sales_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_price',
            new_name='sale_price',
        ),
    ]
